INSERT INTO course_contents (course_id,content_type,title,body,sort_order)
SELECT c.id,v.content_type,v.title,jsonb_build_object('description',v.description),v.sort_order
FROM courses c JOIN (VALUES
('history-culture','video','土尔扈特东归历史专题','真实历史专题课程视频',10),
('history-culture','video','丝绸之路 第一集','央视《丝绸之路》纪录课程',11),
('history-culture','video','丝绸之路 第二集','央视《丝绸之路》纪录课程',12),
('history-culture','video','丝绸之路 第三集','央视《丝绸之路》纪录课程',13),
('history-culture','task','复原土尔扈特东归路线','结合地图与史料标出东归路线关键地点',20),
('history-culture','task','承德建筑证据观察','寻找民族文化交流的建筑证据',21),
('history-culture','task','历史知识测验','完成东归历史知识任务',22),
('history-culture','task','绘制东归路线图','完成东归路线成果图',23),
('history-culture','task','小组分享演讲','准备并完成小组分享',24),
('history-culture','test','东归历史知识测试','东归年份与历史影响测试',30),
('history-culture','test','承德文化遗产辨识','承德文化遗产知识测试',31),
('history-culture','material','土尔扈特东归史料节选','东归背景、行程和安置史料',40),
('history-culture','material','东归路线历史地图','东归路线关键节点地图',41),
('natural-science','video','神农架自然地理 第1集','神农架自然地理纪录课程',10),
('natural-science','video','神农架自然地理 第2集','神农架自然地理纪录课程',11),
('natural-science','video','神农架自然地理 第3集','神农架自然地理纪录课程',12),
('natural-science','video','神农架自然地理 第4集','神农架自然地理纪录课程',13),
('natural-science','task','完成草原植物样方调查','记录植物种类、数量、高度与覆盖度',20),
('natural-science','task','寻找动物活动痕迹','规范记录动物活动痕迹',21),
('natural-science','test','生态系统组成测试','生态系统组成知识测试',30),
('natural-science','test','野外观察规范测试','野外观察安全规范测试',31),
('natural-science','material','草原常见植物识别表','草原植物观察图鉴',40),
('natural-science','material','野外调查安全手册','野外调查必读安全要求',41),
('frontier-technology','video','文昌航天发射场 第1集','文昌航天发射场纪录课程',10),
('frontier-technology','video','文昌航天发射场 第2集','文昌航天发射场纪录课程',11),
('frontier-technology','task','制作火箭结构模型','完成运载火箭分级结构模型',20),
('frontier-technology','task','规划卫星应用方案','设计卫星数据应用方案',21),
('frontier-technology','test','运载火箭基础测试','运载火箭基础知识测试',30),
('frontier-technology','test','卫星应用场景测试','卫星应用知识测试',31),
('frontier-technology','material','中国航天发展时间轴','中国航天工程发展资料',40),
('frontier-technology','material','文昌发射场参观规范','文昌发射场参观要求',41),
('arts-humanities','video','丝路艺术与人文 第1集','丝路艺术与人文纪录课程',10),
('arts-humanities','video','丝路艺术与人文 第2集','丝路艺术与人文纪录课程',11),
('arts-humanities','video','丝路艺术与人文 第3集','丝路艺术与人文纪录课程',12),
('arts-humanities','video','丝路艺术与人文 第4集','丝路艺术与人文纪录课程',13),
('arts-humanities','task','提取敦煌壁画色彩','观察并提取敦煌壁画色彩',20),
('arts-humanities','task','记录园林框景构图','记录园林框景、借景和对景',21),
('arts-humanities','test','园林造景方法测试','园林造景方法知识测试',30),
('arts-humanities','test','敦煌艺术常识测试','敦煌艺术与保护常识测试',31),
('arts-humanities','material','敦煌壁画线描图例','敦煌艺术观察资料',40),
('arts-humanities','material','苏州园林空间观察表','园林空间观察工具',41),
('red-education','video','民族团结与家国情怀','家国情怀专题课程',10),
('red-education','video','中华文明交流 第一讲','中华文明交流课程',11),
('red-education','video','中华文明交流 第二讲','中华文明交流课程',12),
('red-education','task','革命旧址证据寻访','寻找历史事件的现场证据',20),
('red-education','task','红色家书朗读与讨论','分析家书背景、情感和价值选择',21),
('red-education','test','井冈山历史知识测试','井冈山历史知识测试',30),
('red-education','test','旧址参观规范测试','革命旧址参观规范测试',31),
('red-education','material','井冈山革命史时间轴','井冈山革命史资料',40),
('red-education','material','红色研学史料使用指南','史料使用方法资料',41),
('social-practice','video','生态考察实践 第1课','生态考察实践课程',10),
('social-practice','video','生态考察实践 第2课','生态考察实践课程',11),
('social-practice','video','生态考察实践 第3课','生态考察实践课程',12),
('social-practice','video','生态考察实践 第4课','生态考察实践课程',13),
('social-practice','task','完成社区公共空间调查','调查公共空间使用情况',20),
('social-practice','task','开展职业人物访谈','完成结构化职业访谈',21),
('social-practice','test','访谈方法测试','人物访谈方法测试',30),
('social-practice','test','实践安全测试','社会实践安全测试',31),
('social-practice','material','半结构化访谈提纲模板','社会访谈工具模板',40),
('social-practice','material','社会调查隐私保护指南','调查隐私保护要求',41)
) AS v(slug,content_type,title,description,sort_order) ON c.slug=v.slug
WHERE NOT EXISTS (SELECT 1 FROM course_contents cc WHERE cc.course_id=c.id AND cc.title=v.title);
